### ISSUE TITLE
installation from downloaded package does not work

### ISSUE THREAD

**Issue by ignavan39** [volitank/nala#5] opened 2022-04-30 20:30 UTC
```bash
sudo nala install ./Yandex.deb 
```

### output:
![image](https://user-images.githubusercontent.com/68580920/166121583-c8094009-36f2-49f4-a812-f1c90c228d82.png)

**Comment by volitank** [comment] 2022-05-06 02:19
Hi sorry for the late response. We don't usually check for issues here as the GitLab is the official repository.

A couple of questions for you.

What version are you currently on?

And for the output of the exception I'll need the whole thing, I know it's long but you can post it to pastebin or something.

I actually need to fix that, the pretty exceptions are more of a pain than I anticipated.

**Comment by volitank** [comment] 2022-05-23 21:47
Closing as there has been no communication and I'm unable to reproduce. If you're still experiencing this please open an issue on our GitLab

**Closed by volitank** 2022-05-23 21:47 UTC
